id: P000147
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བསྐྱེད་རིམ་སྤྱིའི་རྣམ་ངེས་དང་བསྙེན་སྒྲུབ་མཚམས་ཀྱི་སྤྱི་གནད་མདོར་བསྡུས་པ་རབ་གསལ་ནོར་བུའི་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། པདྨ་གར་དབང་བློ་གྲོས་མཐའ་ཡས།
  layers:
  - book_title
  - author
  id: SHE-RTD-16
web_metadata:
  title:
    en: The Illuminating Jewel Lamp:A Detailed Explanation of  the General Creation
      Stages and a Condensed Presentation of Sadhana Practice
    bo: བསྐྱེད་རིམ་སྤྱིའི་རྣམ་ངེས་དང་བསྙེན་སྒྲུབ་མཚམས་ཀྱི་སྤྱི་གནད་མདོར་བསྡུས་པ་རབ་གསལ་ནོར་བུའི་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 16
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༡༦
  author:
    en: Pema Garwang Lodro Thaye
    bo: པདྨ་གར་དབང་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-16
  category:
    en: Deity Practice
    bo: བསྐྱེད་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-16.epub
  description:
    en: ''
    bo: ''
